// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmFt3qL1I8z_sJ8qIHjV2oJQIXgM5qWmI',
    appId: '1:846324731937:web:b661c09f54099621ea1360',
    messagingSenderId: '846324731937',
    projectId: 'deltanode-a955c',
    authDomain: 'deltanode-a955c.firebaseapp.com',
    storageBucket: 'deltanode-a955c.appspot.com',
    measurementId: 'G-88XBKBQG32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_yDQ4aQ2pEnjwtOM0Oou4VPs2L3fI0TE',
    appId: '1:846324731937:android:1262b3a97f00fb89ea1360',
    messagingSenderId: '846324731937',
    projectId: 'deltanode-a955c',
    storageBucket: 'deltanode-a955c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASBAUCCt3feE9tBXLH30a2UdmBW7SnkPU',
    appId: '1:846324731937:ios:36eaaf1fae5fd81bea1360',
    messagingSenderId: '846324731937',
    projectId: 'deltanode-a955c',
    storageBucket: 'deltanode-a955c.appspot.com',
    iosClientId: '846324731937-p4aqt9586svn1dgs67drtkeap9dggud3.apps.googleusercontent.com',
    iosBundleId: 'com.example.delta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASBAUCCt3feE9tBXLH30a2UdmBW7SnkPU',
    appId: '1:846324731937:ios:36eaaf1fae5fd81bea1360',
    messagingSenderId: '846324731937',
    projectId: 'deltanode-a955c',
    storageBucket: 'deltanode-a955c.appspot.com',
    iosClientId: '846324731937-p4aqt9586svn1dgs67drtkeap9dggud3.apps.googleusercontent.com',
    iosBundleId: 'com.example.delta',
  );
}
